# Generated by Django 4.0.3 on 2022-03-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='state_name',
            new_name='location_name',
        ),
    ]
