# Generated by Django 4.0.3 on 2022-03-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_rename_state_name_category_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='images',
        ),
    ]
